In [20]:
import pandas as pd
import zipfile

listing_path = r"C:\Users\alrvt\Downloads\listings (2).csv.gz"
listing_df = pd.read_csv(listing_path)

In [21]:

calendar_path = r"C:\Users\alrvt\Downloads\calendar (1).csv.gz"
calendar_df = pd.read_csv(calendar_path)

In [18]:
calendar_df.columns

Index(['listing_id', 'date', 'available', 'price', 'adjusted_price',
       'minimum_nights', 'maximum_nights'],
      dtype='str')

In [22]:
listing_df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2719440,https://www.airbnb.com/rooms/2719440,20250912034503,2025-09-12,previous scrape,Nice flat close to Montparnasse,This beautiful apartment is very well located ...,"The neighborhood is very nice, feel free to sh...",https://a0.muscache.com/pictures/295786e7-116c...,13915159,...,4.94,4.86,4.73,7510702406383,f,1,1,0,0,0.57
1,2721397,https://www.airbnb.com/rooms/2721397,20250912034503,2025-09-12,previous scrape,"Marais - Charming loft, river view","In the heart of historical Paris le Marais, gr...",Le Marais is the heart of Paris. Few years ago...,https://a0.muscache.com/pictures/de55313f-9b4b...,13925876,...,4.95,4.91,4.85,7510400455677,f,1,1,0,0,0.66
2,2726092,https://www.airbnb.com/rooms/2726092,20250912034503,2025-09-12,previous scrape,Superbe 2 pièces idéalement placé,A stone's throw from Parc Monceau and the Arc ...,Quiet and residential area... Close to the Bat...,https://a0.muscache.com/pictures/6d6c4bc6-9473...,13612373,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
3,2726327,https://www.airbnb.com/rooms/2726327,20250912034503,2025-09-12,previous scrape,"Cozy place, Sacré Coeur Montmartre in the SoPi",Cozy apartment close to everything.<br />Perfe...,One of the most trendy corners of the capital ...,https://a0.muscache.com/pictures/6b569382-aed7...,7483725,...,4.97,4.92,4.67,7510901014972,f,1,1,0,0,0.72
4,2727929,https://www.airbnb.com/rooms/2727929,20250912034503,2025-09-12,previous scrape,Appartement d'architecte - Montmartre,"Our apartment, refurbished by an architect in ...",The apartment is in the heart of Paris's 18th ...,https://a0.muscache.com/pictures/miso/Hosting-...,13960346,...,5.00,4.57,5.00,7511808333770,f,1,1,0,0,0.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81848,1481754230424845668,https://www.airbnb.com/rooms/1481754230424845668,20250912034503,2025-09-15,previous scrape,Apt a/c 1BR/2P - Saint-Lazare/Les Champs Elysée,📌 Checkmyguest offers you a charming and spaci...,🏘️ The 8th arrondissement of Paris is one of t...,https://a0.muscache.com/pictures/prohost-api/H...,524851930,...,5.00,5.00,5.00,7510815621419,t,184,184,0,0,2.00
81849,1481771421372168466,https://www.airbnb.com/rooms/1481771421372168466,20250912034503,2025-09-15,previous scrape,Superbe duplex avec terrasse face Tour Eiffel,The Konciergerie is proud to present this char...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,563248085,...,NaN,NaN,NaN,"Available with a mobility lease only (""bail mo...",t,76,76,0,0,NaN
81850,1481789891762355898,https://www.airbnb.com/rooms/1481789891762355898,20250912034503,2025-09-15,previous scrape,Cozy studio - 2P - Place des Vosges/Marais,Checkmyguest offers you an exceptional 24 m² s...,"Romantic, festive and trendy, the Marais distr...",https://a0.muscache.com/pictures/prohost-api/H...,691591816,...,4.00,5.00,4.00,7510406440280,t,3,3,0,0,1.00
81851,1481814132906153972,https://www.airbnb.com/rooms/1481814132906153972,20250912034503,2025-09-15,previous scrape,Appt entier 35m2 proche Montmartre,Quiet 35 m2 apartment in the heart of Paris.<b...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,35944108,...,NaN,NaN,NaN,NaN,f,2,1,1,0,NaN
81852,1481829796903012005,https://www.airbnb.com/rooms/1481829796903012005,20250912034503,2025-09-15,previous scrape,"Nice Flat in West Paris, near the Seine",A newly renovated 3-room apartment designed to...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,255647011,...,5.00,5.00,5.00,7511615734629,t,21,21,0,0,1.00

In [23]:
calendar_df[calendar_df['listing_id'].isin([2719440, 1481829796903012005])]

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,2719440,2025-09-12,f,NaN,NaN,2,7
1,2719440,2025-09-13,f,NaN,NaN,2,7
2,2719440,2025-09-14,f,NaN,NaN,2,7
3,2719440,2025-09-15,f,NaN,NaN,2,7
4,2719440,2025-09-16,f,NaN,NaN,2,7
...,...,...,...,...,...,...,...
29815295,1481829796903012005,2026-09-10,t,NaN,NaN,2,365
29815296,1481829796903012005,2026-09-11,t,NaN,NaN,2,365
29815297,1481829796903012005,2026-09-12,t,NaN,NaN,2,365
29815298,1481829796903012005,2026-09-13,t,NaN,NaN,2,365
29815299,1481829796903012005,2026-09-14,t,NaN,NaN,2,365